spring:
  profiles:
    active:
      - local
    group:
      - site-local
      - db-local
    dev:
      - site-dev
      - db-dev
    include:
      - b
        - my-service
        - sited

# spring-profiles-active  : ????? ???? profile? local? ?????.
# spring-profiles-group  : profile group? ??? ? ????.
# local : profile? local? ?? site-local, db-local ? profile? ??? ?????.
# dev : profile? local? ?? site-dev, db-dev ? profile? ??? ?????.

# spring-profiles-include  ??? ?? ??????? ??? ? profile? ???? ??? ? ????.
#? application-db.yml, application-my-site.yml, application-site.yml ??? ?? profile? ???? ??????? ?????.