server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: oauth2-client-app
            client-secret: kG7F3oTROiynU63RJ9mfiQmcoF5vss59
            client-name: oauth2-client-app
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: client_secret_basic
            scope: openid,profile,email
        provider:
          keycloak:
            authorizationUri: http://localhost:8080/realms/master/protocol/openid-connect/auth
            tokenUri: http://localhost:8080/realms/master/protocol/openid-connect/token
            jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
            token-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

