server:
  port: 8081



spring:
  security:
    oauth2:
      client:
        registration:
#          github:
#            client-id: d4b4474600668e6135ae
#            client-secret: 8348bbacd9954b808b503e600448fa97b57abc3e
          keycloak:
            client-id: oauth2-client-app
            client-secret: kG7F3oTROiynU63RJ9mfiQmcoF5vss59
            client-name: oauth2-client-app
            redirectUri: http://localhost:8081/login/oauth2/code/keycloak
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: client_secret_post
            scope: openid,profile,email
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
            issuer-uri: http://localhost:8080/realms/oauth2
            jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
            token-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

